version: '3.4'

services:
    identity.microservice.db:
        container_name: identity.microservice.db
        image: postgres:17.0-alpine3.20
        environment:
            POSTGRES_DB: "ast-help-identity"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - identity.microservice.db:/var/lib/postgresql/data
        ports:
            - "5400:5432"
    catalog.microservice.db:
        container_name: catalog.microservice.db
        image: postgres:17.0-alpine3.20
        environment:
            POSTGRES_DB: "ast-help-catalog"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - catalog.microservice.db:/var/lib/postgresql/data
        ports:
            - "5401:5432"
    cart.microservice.db:
        container_name: cart.microservice.db
        image: postgres:17.0-alpine3.20
        environment:
            POSTGRES_DB: "ast-help-cart"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - cart.microservice.db:/var/lib/postgresql/data
        ports:
            - "5402:5432"
    orders.microservice.db:
        container_name: orders.microservice.db
        image: postgres:17.0-alpine3.20
        environment:
            POSTGRES_DB: "ast-help-orders"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - orders.microservice.db:/var/lib/postgresql/data
        ports:
            - "5403:5432"

    identity.microservice.api:
        image: identity.microservice.api
        container_name: identity.microservice.api
        build:
            context: ../../Microservice/Identity
            dockerfile: ./Identity.Microservice.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=identity.microservice.db;Port=5432;Database=ast-help-identity;User Id=postgres;Password=1234
        ports:
            - "5100:80"
        depends_on:
            - identity.microservice.db
    catalog.microservice.api:
        image: catalog.microservice.api
        container_name: catalog.microservice.api
        build:
            context: ../../Microservice/Catalog
            dockerfile: ./Catalog.Microservice.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=catalog.microservice.db;Port=5432;Database=ast-help-catalog;User Id=postgres;Password=1234
        ports:
            - "5101:80"
        depends_on:
            - catalog.microservice.db
    cart.microservice.api:
        image: cart.microservice.api
        container_name: cart.microservice.api
        build:
            context: ../../Microservice/Cart
            dockerfile: ./Cart.Microservice.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=cart.microservice.db;Port=5432;Database=ast-help-cart;User Id=postgres;Password=1234
        ports:
            - "5102:80"
        depends_on:
            - cart.microservice.db
    orders.microservice.api:
        image: orders.microservice.api
        container_name: orders.microservice.api
        build:
            context: ../../Microservice/Orders
            dockerfile: ./Orders.Microservice.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=orders.microservice.db;Port=5432;Database=ast-help-orders;User Id=postgres;Password=1234
        ports:
            - "5103:80"
        depends_on:
            - orders.microservice.db

    asthelp.gateway:
        image: asthelp.gateway
        container_name: asthelp.gateway
        build:
            context: ../../Gateway.WebApi
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        ports:
            - "80:80"
        depends_on:
            - identity.microservice.api
volumes:
    identity.microservice.db:
        name: identity.microservice.db 
    catalog.microservice.db:
        name: catalog.microservice.db 
    cart.microservice.db:
        name: cart.microservice.db   
    orders.microservice.db:
        name: orders.microservice.db            
