services:
    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"

    identity.microservice.db:
        environment:
            POSTGRES_DB: "ast_help_identity"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5400:5432"
    catalog.microservice.db:
        environment:
            POSTGRES_DB: "ast_help_catalog"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5401:5432"
    cart.microservice.db:
        environment:
            POSTGRES_DB: "ast_help_cart"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5402:5432"
    orders.microservice.db:
        environment:
            POSTGRES_DB: "ast_help_orders"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5403:5432"
    notification.microservice.db:
        environment:
            POSTGRES_DB: "ast_help_notification"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5404:5432"
                            
    identity.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=identity.microservice.db;Port=5432;Database=ast_help_identity;User Id=postgres;Password=1234
            - RabbitMQ__HostName=rabbitmq
            - RabbitMQ__Port=5672
            - RabbitMQ__UserName=user
            - RabbitMQ__Password=password
            - RabbitMQ__QueueName=IdentityQueue
            - RabbitMQ__ExchangeName=IdentityExchange
        ports:
            - "5100:80"
    catalog.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=catalog.microservice.db;Port=5432;Database=ast_help_catalog;User Id=postgres;Password=1234
            - RabbitMQ__HostName=rabbitmq
            - RabbitMQ__Port=5672
            - RabbitMQ__UserName=user
            - RabbitMQ__Password=password
            - RabbitMQ__QueueName=CatalogQueue
            - RabbitMQ__Exchange=CatalogExchange
        ports:
            - "5101:80"
    cart.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=cart.microservice.db;Port=5432;Database=ast_help_cart;User Id=postgres;Password=1234
            - RabbitMQ__HostName=rabbitmq
            - RabbitMQ__Port=5672
            - RabbitMQ__UserName=user
            - RabbitMQ__Password=password
            - IdentityService__BaseUrl=http://identity.microservice.api/
            - CatalogService__BaseUrl=http://catalog.microservice.api/
        ports:
            - "5102:80"
    orders.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=orders.microservice.db;Port=5432;Database=ast_help_orders;User Id=postgres;Password=1234
            - RabbitMQ__HostName=rabbitmq
            - RabbitMQ__Port=5672
            - RabbitMQ__UserName=user
            - RabbitMQ__Password=password
            - IdentityService__BaseUrl=http://identity.microservice.api/
            - CatalogService__BaseUrl=http://catalog.microservice.api/
            - CartService__BaseUrl=http://cart.microservice.api/
        ports:
            - "5103:80"
    notification.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=notification.microservice.db;Port=5432;Database=ast_help_notification;User Id=postgres;Password=1234
            - RabbitMQ__HostName=rabbitmq
            - RabbitMQ__Port=5672
            - RabbitMQ__UserName=user
            - RabbitMQ__Password=password
            - RabbitMQ__QueueName=NotificationQueue
        ports:
            - "5104:80"

    asthelp.gateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        ports:
            - "5000:80"

    asthelp.webapp:
        environment:
            - REACT_APP_API_URL=http://asthelp.gateway/api/
        ports:
            - "80:80"
