services:
    rabbitmq:
        container_name: rabbitmq
        build: 
            context: ./rabbitmq_config
            dockerfile: Dockerfile
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    identity.microservice.db:
        container_name: identity.microservice.db
        image: postgres:17.0-alpine3.20
        restart: on-failure
        volumes:
            - identity.microservice.db:/var/lib/postgresql/data
    catalog.microservice.db:
        container_name: catalog.microservice.db
        image: postgres:17.0-alpine3.20
        restart: on-failure
        volumes:
            - catalog.microservice.db:/var/lib/postgresql/data
    cart.microservice.db:
        container_name: cart.microservice.db
        image: postgres:17.0-alpine3.20
        restart: on-failure
        volumes:
            - cart.microservice.db:/var/lib/postgresql/data
    orders.microservice.db:
        container_name: orders.microservice.db
        image: postgres:17.0-alpine3.20
        restart: on-failure
        volumes:
            - orders.microservice.db:/var/lib/postgresql/data
    notification.microservice.db:
        container_name: notification.microservice.db
        image: postgres:17.0-alpine3.20
        restart: on-failure
        volumes:
            - notification.microservice.db:/var/lib/postgresql/data

    identity.microservice.api:
        image: identity.microservice.api
        container_name: identity.microservice.api
        restart: on-failure
        build:
            context: ../../Microservice/Identity
            dockerfile: ./Identity.Microservice.API/Dockerfile
        depends_on:
            - identity.microservice.db
            - rabbitmq
    catalog.microservice.api:
        image: catalog.microservice.api
        container_name: catalog.microservice.api
        restart: on-failure
        build:
            context: ../../Microservice/Catalog
            dockerfile: ./Catalog.Microservice.API/Dockerfile
        depends_on:
            - catalog.microservice.db
            - rabbitmq
    cart.microservice.api:
        image: cart.microservice.api
        container_name: cart.microservice.api
        restart: on-failure
        build:
            context: ../../Microservice/Cart
            dockerfile: ./Cart.Microservice.API/Dockerfile
        depends_on:
            - cart.microservice.db
            - rabbitmq
    orders.microservice.api:
        image: orders.microservice.api
        container_name: orders.microservice.api
        restart: on-failure
        build:
            context: ../../Microservice/Orders
            dockerfile: ./Orders.Microservice.API/Dockerfile
        depends_on:
            - orders.microservice.db
            - rabbitmq
    notification.microservice.api:
        image: notification.microservice.api
        container_name: notification.microservice.api
        restart: on-failure
        build:
            context: ../../Microservice/Notification
            dockerfile: ./Notification.Microservice.API/Dockerfile
        depends_on:
            - notification.microservice.db
            - rabbitmq

    asthelp.gateway:
        image: asthelp.gateway
        container_name: asthelp.gateway
        restart: on-failure
        build:
            context: ../../Gateway.WebApi
            dockerfile: ./Dockerfile
        depends_on:
            - identity.microservice.api
            - catalog.microservice.api
            - cart.microservice.api
            - orders.microservice.api
            - notification.microservice.api

    asthelp.webapp:
        image: asthelp.webapp
        container_name: asthelp.webapp
        build:
            context: ../../AstHelp.Webapp
            dockerfile: ./Dockerfile
        depends_on:
            - asthelp.gateway

volumes:
    rabbitmq_data:
        name: rabbitmq_data   
        driver: local

    identity.microservice.db:
        name: identity.microservice.db 
    catalog.microservice.db:
        name: catalog.microservice.db 
    cart.microservice.db:
        name: cart.microservice.db   
    orders.microservice.db:
        name: orders.microservice.db  
    notification.microservice.db:
        name: notification.microservice.db            
