version: '3.4'

services:
    identity.microservice.db:
        environment:
            - MYSQL_DATABASE=UserDb
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_USER=user
            - MYSQL_PASSWORD=1234
            - MYSQL_TCP_PORT=3307
        volumes:
            - identity.microservice.db:/var/lib/mysql/identity/ 
        ports:
            - '3307:3307'
    identity.microservice.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5000
            - ConnectionStrings__Database=Server=identity.microservice.db;Port=3307;Database=UserDb;User Id=user;Password=1234
        ports:
            - "5000:5000"
